language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - cargo install cargo-travis

after_script:
  - cargo coveralls
